version: '2'
services:
  nginx:
    #build: nginx
    image: gds_nginx
    command: nginx -g "daemon off;"
    links:
      - tomcat
    container_name: app_nginx
    ports:
      - "5000:80"
  tomcat:
    #build: tomcat
    image: gds_tomcat
    working_dir: /usr/local/tomcat
    command: catalina.sh run
    container_name: app_tomcat
    ports:
      - "8080:8080"
